// src/components/layout.tsx
import { useStaticQuery, graphql } from 'gatsby';
import { clsx } from 'clsx';
import { Header } from './Header';
import { Footer } from './Footer';
import React from 'react';
import { SkipToMain } from './SkipToMain';

interface LayoutProps {
  children: React.ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  const data = useStaticQuery(graphql`
    query SiteTitleQuery {
      site {
        siteMetadata {
          title
        }
      }
    }
  `);

  return (
    <div className="min-h-screen flex flex-col bg-light-background dark:bg-dark-background bg-top-gradient">
      <SkipToMain />
      <Header siteTitle={data.site.siteMetadata?.title || `Title`} />
      <main
        id="main"
        className={clsx('text-light-text dark:text-dark-text', 'pt-24 md:pt-32 pb-12 flex-1')}>
        {children}
      </main>
      <Footer />
    </div>
  );
};

export default Layout;

// src/components/Layout.vue
<template>
  <div className="min-h-screen flex flex-col bg-light-background dark:bg-dark-background bg-top-gradient">
    <SkipToMain />
    <Header site-title="dhemeira" />
    <main id="main" :class="['text-light-text dark:text-dark-text', 'pt-24 md:pt-32 pb-12 flex-1']">
      <slot></slot>
    </main>
    <Footer />
  </div>
</template>

<script setup lang="ts">
import Header from './Header.vue';
import Footer from './Footer.vue';
import SkipToMain from './SkipToMain.vue';
</script>
